apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka-py2
  ports:
    - port: 8000
      targetPort: 8000
      #nodePort: 31000
  type: LoadBalancer
  #type: NodePort
